spring.application.name=backend

# MySQL Connection
# spring.datasource.url=jdbc:mysql://127.0.0.1:3306/meetscribe
# spring.datasource.username=root
# spring.datasource.password=ayush

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Session
server.port==${PORT:8080}
server.servlet.session.timeout=30m
# spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration